= Vlna: Nástroj pro rozesílání hromadné pošty
:numbered:
:icons: font
:lang: cs
:note-caption: Poznámka
:warning-caption: Pozor
:table-caption: Tabulka
:figure-caption: Obrázek
:example-caption: Příklad
:toc-title: Obsah
:toc: left
:toclevels: 2
:sectnumlevels: 6
:source-highlighter: pygments

== LDAP

Adresář se využívá především pro čtení, ale v omezené míře i pro zápis informací o příjemcích pošty a distribučních kanálech.

=== `OU=Mailing,O=Pirati`

Distribuční kanály, které systém prohledává. Obsahuje následující atributy:

`senderGroup` (multi, dn)::
Seznam skupin, jejichž členové jsou oprávněni odesílat zprávy skrze daný distribuční kanál.

`recipientGroup` (multi, dn)::
Seznam skupin, jejichž členové jsou výchozími příjemci tohoto distribučního kanálu.

`public` (boolean)::
Pokud je `true`, kdokoliv se může přihlásit k příjmu tohoto distribučního kanálu. Aplikace pak bere v potaz obsah pole `optIn`.

`optIn` (multi, dn)::
Seznam uživatelů, kteří explicitně žádají o příjem zpráv z tohoto distribučního kanálu bez ohledu na své členství ve skupinách.

`optOut` (multi, dn)::
Seznam uživatelů, kteří explicitně žádají o vyřazení z tohoto distribučního kanálu navzdory svému členství ve skupinách.

`template` (string)::
Název šablony, která má být použita při rozesílání.

<<<

== Databáze

=== Tabulka `campaign`

`id` (bigint)::
Identifikátor kampaně.

`name` (character varying)::
Popisný název kampaně.

`author` (character varying)::
Zadavatel kampaně, identifikovaný plným DN v textové formě.

`mailing` (character varying)::
Distribuční kanál, identifikovaný plným DN v textové formě.

`state` (enum)::
Stav kampaně, který se z `draft` mění na `pending` a následně na `sent` dle skutečného stavu.

`start` (timestamp with time zone)::
Čas odeslání kampaně.

`content` (text)::
Text zprávy ve formátu Markdown.


// vim:set spelllang=cs,en:
